env:
  MANIFEST: https://github.com/AlphaDroid-Project/manifest.git
  MANIFEST_BRANCH: alpha-13
  DEVICE: rova
  OEM: xiaomi
  DT_LINK: https://github.com/Maxx12211/android_device_xiaomi_rova.git -b 13.0-alphadroid
  DT_PATH: device/$OEM/$DEVICE
  VT_LINK: https://github.com/Maxx12211/android_vendor_xiaomi_rova.git -b 13
  VT_PATH: vendor/$OEM/$DEVICE
  KT_LINK: https://github.com/Maxx12211/android_kernel_xiaomi_rova.git -b 13.0
  KT_PATH: kernel/$OEM/$DEVICE
  LUNCH_COMBO: lineage_rova-user
  TARGET: bacon
  OUTPUT: AlphaDroid*.zip

  # Not Recommended to Change
  SYNC_PATH: $HOME/work # Do NOT use "~". Use $HOME instead.
  CCACHE_SIZE: 30G
  CCACHE_DIR: $HOME/work/.ccache
  J_VAL: 16

  # Cirrus Specific Vars (Do *NOT* Change)
  CIRRUS_SHELL: bash

task:
  name: "AlphaDroid Build"
  timeout_in: 2h
  container:
    image: apon77/aosp:cirrus
    cpu: 8
    memory: 32G

  Storage_Checker:
    - df -h
    - lsblk
    - ls -l -a -h

  Sync_script:
    - bash sync.sh

  Build_script:
    - bash build.sh

  Upload_script:
    - export TIMEOUT=43200 # Download Link Timeout (in Minutes)
    - bash upload.sh
